
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX imas: <https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT *
WHERE {
  ?idol rdf:type imas:Idol.
  optional { ?idol schema:name ?name_ja. filter( lang(?name_ja) = 'ja') }.
  optional { ?idol schema:name ?name_en. filter( lang(?name_en) = 'en') }.
  optional { ?idol imas:nameKana ?nameKana. }.
  optional { ?idol schema:height ?height. }.
  optional { ?idol schema:weight ?weight. }.
  optional { ?idol schema:gender ?gender. }.
  optional { ?idol imas:BloodType ?bloodType. }.
  optional { ?idol foaf:age ?age. }.
}
order by ?nameKana
limit 10
